platform :ios    
pod 'Reachability',  '~> 3.0.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'JSBadgeView'

platform :ios, '6.0'
pod "AFNetworking", "~> 2.0"


post_install do |installer|

installer.project.targets.each do |target|

target.build_configurations.each do |config|

config.build_settings['ARCHS'] = "armv7s armv7"

end

end

end

